######################################################################
# Automatically generated by qmake (3.0) Mo Jun 6 08:49:00 2016
######################################################################

TEMPLATE = app
TARGET = detect-emotion
INCLUDEPATH += .

# Input
HEADERS += header/actionunit.h \
           header/controls.h \
           header/myendian.h \
           header/reader.h \
           header/utils.h \
           src/qviewer/qdataloader.h \
           build/mingw32/debug/src/qviewer/moc_qdataloader.cpp
SOURCES += src/controls.cpp \
           src/keytest.cpp \
           src/playall.cpp \
           src/playone.cpp \
           bin/CMakeFiles/feature_tests.cxx \
           src/qviewer/main.cpp \
           src/qviewer/qdataloader.cpp \
           bin/CMakeFiles/3.5.2/CompilerIdC/CMakeCCompilerId.c \
           bin/CMakeFiles/3.5.2/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           build/mingw32/debug/CMakeFiles/feature_tests.c \
           build/mingw32/debug/CMakeFiles/feature_tests.cxx \
           build/mingw32/release/CMakeFiles/feature_tests.c \
           build/mingw32/release/CMakeFiles/feature_tests.cxx \
           build/mingw32/debug/src/qviewer/qrc_qml.cpp \
           build/mingw32/debug/src/qviewer/qviewer_automoc.cpp \
           build/mingw32/debug/CMakeFiles/3.5.2/CompilerIdC/CMakeCCompilerId.c \
           build/mingw32/debug/CMakeFiles/3.5.2/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           build/mingw32/release/CMakeFiles/3.5.2/CompilerIdC/CMakeCCompilerId.c \
           build/mingw32/release/CMakeFiles/3.5.2/CompilerIdCXX/CMakeCXXCompilerId.cpp
RESOURCES += src/qviewer/qml.qrc
